CREATE VIEW TITLE_UNAVAIL
AS SELECT TITLE,MEDIA_ID,RETURN_DATE
FROM MEDIA JOIN MOVIES USING (TITLE_ID) JOIN RENTAL_HISTORY USING (MEDIA_ID)
WHERE RETURN_DATE<CURRENT_DATE;

CREATE SEQUENCE CUSTOMER_ID_SEQ
INCREMENT BY 1
START WITH 101
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE SEQUENCE TITLE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE SEQUENCE MEDIA_ID_SEQ
INCREMENT BY 1
START WITH 92
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE SEQUENCE ACTOR_ID_SEQ
INCREMENT BY 1
START WITH 1001
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE INDEX IX_CUSTOMER_LAST_NAME
ON CUSTOMER(LAST_NAME);

CREATE SYNONYM TU
FOR TITLE_UNAVAILABLE;